### ISSUE TITLE
Is conditional compile required for testnet?

### ISSUE THREAD

**Issue by eriksank** [libbitcoin/libbitcoin-explorer#369] opened 2016-06-18 12:50 UTC
Every time I see the `bx` tool, I think by myself: this is exactly what I need. `So, let's test it.` 

Unfortunately, that also means that I will not be testing any time soon, because I would have to painstakingly build the testnet version. The last time that I tried to build anything that depends on boost, I wasn't particularly happy. The experience was not really "exhilarating". 

I have never tested on the mainnet. I always do all of my tests on testnet, with bitcoind running in regtest mode. It works absolutely fine, and I do not need to use real money to figure out what is happening.

You see, there is nothing in `bx` that requires underlying system software that was not available on a 1979 system V computer. In that sense, it should be able to happily build and run on an ancient PDP-11. But then again, I seriously doubt that it would build even on a machine that happened to be installed in 2010. Therefore, most contemporary build processes just irritate me.

Of course, there is also the question why the tool requires a complete rebuild just for a few constants that are different between mainnet and testnet? Most of my production work rests on an absolutely vulgar piece of script library written in PHP, of all questionable language choices, yes indeed that one. It switches between testnet and mainnet on the fly.

The code has been running almost 1.5 years in production now, serving tens of thousands of users. So, it is certainly not that bad. It would be trivially easy to add another "net" to that thing. So, that lousy PHP thing can again do things that the vastly superior C++ alternative cannot. This seems to happen all the time, actually. The stuff touted as theoretically better just cannot do it. Only that silly PHP stuff seems to work ...

The last time that I visited the `bx` repo, is almost a year ago, in 2015. Maybe I should try again in 2018? Maybe someone in your team will build the testnet version and put it up for download? Maybe they will finally address this show stopper? I somehow don't think so, but ok, it does not cost me anything to inquire, does it? ;-)

Talk to you again in 2018!

**Comment by evoskuil** [comment] 2016-06-18 13:28
Is there a question, or a problem here?

First, Turing machines can implement any logic. So quite clearly there is no requirement for dependencies. Dependencies such as zeromq, secp256k1 and boost are used to reduce cost and improve quality.

Second, bx not only runs on Linux, Windows and OSX, but it is primarily developed on these platforms using hardware from 2010 (Dell Optiplex 780).

Third, the current version3 [master] build does not require conditional build for testnet - the distinction is managed by config and supports most other coins similarly.

Finally, building version2 or version3 requires the execution of a single command (install.sh) and does not even require sudo.

It's better to learn before ranting.

**Comment by RojavaCrypto** [comment] 2016-06-18 20:55
I am using the new Ubuntu, and you can try this:

sudo apt-get install build-essential autoconf automake libtool pkg-config git libboost-all-dev
wget https://raw.githubusercontent.com/libbitcoin/libbitcoin-explorer/version2/install.sh
sudo bash install.sh

And it should work for testnet. See the config file /usr/local/etc/libbitcoin/bx.cfg

Maybe the README could be a bit clearer about this.

Check out the [network] section:

https://github.com/libbitcoin/libbitcoin-explorer/blob/master/data/bx.cfg

And `use_testnet_rules' here:

https://github.com/libbitcoin/libbitcoin-server/blob/master/data/bs.cfg

Pretty cool huh. You can configure everything.

**Comment by RojavaCrypto** [comment] 2016-06-18 21:00
See example 2 here for the testnet config file:

https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-settings

**Comment by evoskuil** [comment] 2016-06-18 21:16
Note that the install.sh link above is for version2, which does require conditional build. I think this was intended to be master.

**Comment by eriksank** [comment] 2016-06-19 00:51
@RojavaCrypto: Thanks for the instructions, but you see, I have been burnt a few times too often trying to build something that mentions the dependency `boost`.
I just see it anywhere mentioned and my nerves already start playing up.

The furthest that I agree to go is to build something that was "autoconfiscated". I also hate that particular stuff with a passion, but I must admit that I did manage to build even things that starting spewing error messages about missing .m4 macros.

The only subsystem that I remember to be utterly unbuildable is `boost`. The idea of building something again, that contains `boost`, is just too much. The `boost` build is not reproducible and not idempotent. `boost` has other bad characteristics that you can only describe correctly by using category theory and universal algebra. It even has properties at a more metaphysical level that we can only qualify as satanic. `boost` even said to have embedded statements that decribe the end of the universe. It is known to be the work of the devil. I will not build it again on my machine. Seriously, I will not do it.

**Comment by evoskuil** [comment] 2016-06-19 04:23
$ install.sh --build-boost

**Comment by evoskuil** [comment] 2016-06-19 05:24
Closing this as there is no actual question or problem indicated.

**Closed by evoskuil** 2016-06-19 05:24 UTC
Labels: question

**Comment by RojavaCrypto** [comment] 2016-06-19 10:24
Welcome to 2016. I hate JavaScript, but all the new programmers code web apps in JS. Times change. I'm a fan of old-style modular UNIX daemons, plain text and sockets.

**Comment by eriksank** [comment] 2016-06-19 10:44
@RojavaCrypto Well, me too. Bash is the love of my life.

I have disavowed javascript to an important extent. Unfortunately, I cannot repudiate JS for 100% because it is the only language that runs in a browser.

I did a few npm modules in the past, but I am done with that now. I will no longer do nodejs.

I am also seeking to repudiate the browser itself, if possible somehow. That is really a long-term project to do that, however. It is hard to book rapid results in that realm. In the meanwhile, I will just have to suffer javascript and the browser, and the other 2016 stuff that I so much dislike.

You see, it is easier to get away with avoiding to build `boost`.

There is indeed an annoying price tag attached, because that means that I cannot use bx in testnet mode, and that means that I cannot use bx altogether; because it would mean that bx would be utterly untestable to me.

But then again, I am already  beholden to so much stuff that I do not particularly like ("compromises"), that I really do not want to increase the size of that collection.

So, if the bx team does not put up a prebuilt testnet version for download, I will just forego the possibility to use it, and stick to the obnoxious PHP crap that I am using now. ;-)

**Comment by RojavaCrypto** [comment] 2016-06-19 11:36
OK, well we are coming out a version 3 soon which will be the most stable release ever and have dynamic support for runtime switching between testnet, mainnet and other nets (so you can configure your own blockchains). Also we will have Debian packages. There's already a repo that we should publish.

**Comment by RojavaCrypto** [comment] 2016-06-19 11:38
https://wiki.unsystem.net/en/index.php/Libbitcoin/Repositories
