### ISSUE TITLE
libbitcoin-explorer 3.7.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [libbitcoin/libbitcoin-explorer#730] opened 2023-08-14 14:33 UTC
libbitcoin-explorer 3.7.0 requires libbitcoin-client >= 3.7.0, but there is no libbitcoin-client  3.7.0 release, did I miss anything?

relates to https://github.com/Homebrew/homebrew-core/pull/139514

cc @kulpreet

**Comment by evoskuil** [comment] 2023-08-14 19:10
It seems that the versioning (xml metadata) was also bumped for bx dependencies. @kulpreet ?

**Comment by kulpreet** [comment] 2023-08-14 19:20
We are looking into this with @pmienk

**Comment by kulpreet** [comment] 2023-08-14 20:10
@pmienk explained to me that without updating the build output for explorer, it is trying to get the same version number as itself for other libs. This seems to be the behaviour for the past couple of releases.

We have two options:

1. Rollback v3.7.0 on explorer.
2. Ship new versions for all other libs to match explorer's version.

I like 1, cause it is less destructive. We can figure out how to decouple versions and/or do 2. later once you are settled in have internet.

**Comment by evoskuil** [comment] 2023-08-14 20:57
It’s been a while since I looked at versioning, but I thought we were decoupled and the consistency across repo versions was only a convention (and possibly a default). But if that’s not the case I agree, 1 is less disruptive - just remove the tag until we bump the version.

**Comment by kulpreet** [comment] 2023-08-15 07:14
Removed the v3.7.0 release and tag. Posted on the related issue on homebrew-core. Waiting to see if the issue is auto-resolved or @chenrui333 needs to do something to clear that out.

**Comment by pmienk** [comment] 2023-08-15 08:54
@kulpreet, @evoskuil - As the last versioned release v3.6.0 across all repositories was performed in 2019, there have been significant changes which will prevent the current master of libbitcoin-explorer from compiling against the previous releases.  There are 133 changes from v3.6.0 in libbitcoin-system alone.  While many are build tooling changes, there are a significant number of code changes that will prevent building on updated compilers.

For consistency, I would advocate for pushing v3.7.0 across all repositories after poking CI to reconfirm their success.

**Comment by ZenulAbidin** [comment] 2023-08-15 11:57
> @pmienk explained to me that without updating the build output for explorer, it is trying to get the same version number as itself for other libs. This seems to be the behaviour for the past couple of releases.
> 
> We have two options:
> 
> 1. Rollback v3.7.0 on explorer.
> 2. Ship new versions for all other libs to match explorer's version.
> 
> I like 1, cause it is less destructive. We can figure out how to decouple versions and/or do 2. later once you are settled in have internet.

Is it not possible to modify the build system parameters in the long term so that different versions of libbitcoin libraries can be pulled at the same time?

That would avoid dependency hell of synchronizing multiple projects to the same release.

**Comment by evoskuil** [comment] 2023-08-15 12:04
One can always pull whatever version he wants, but the libraries must be compatible. The reason for versioning is in part to manage incompatibility.

**Comment by pmienk** [comment] 2023-08-15 12:45
Builds verifying version3 HEAD (with explicit dependency upon v3.7.0):

- [libbitcoin-system](https://github.com/libbitcoin/libbitcoin-system/actions/runs/5865380948)
- [libbitcoin-protocol](https://github.com/libbitcoin/libbitcoin-protocol/actions/runs/5865386014)
- [libbitcoin-client](https://github.com/libbitcoin/libbitcoin-client/actions/runs/5865498923)
- [libbitcoin-network](https://github.com/libbitcoin/libbitcoin-network/actions/runs/5865511334)
- [libbitcoin-explorer](https://github.com/libbitcoin/libbitcoin-explorer/actions/runs/5865548484)
- [libbitcoin-consensus](https://github.com/libbitcoin/libbitcoin-consensus/actions/runs/5865524906)
- [libbitcoin-database](https://github.com/libbitcoin/libbitcoin-database/actions/runs/5865532200)
- [libbitcoin-blockchain](https://github.com/libbitcoin/libbitcoin-blockchain/actions/runs/5865534488)
- [libbitcoin-node](https://github.com/libbitcoin/libbitcoin-node/actions/runs/5865541428)
- [libbitcoin-server](https://github.com/libbitcoin/libbitcoin-server/actions/runs/5865545767)

**Comment by pmienk** [comment] 2023-08-18 14:51
Issue resolved by coordinated v3.8.0 release.

**Closed by pmienk** 2023-08-18 14:51 UTC
Labels: build
